### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by AnotherWayIn** [thec00n/Uploader#1]
I've installed the latest JRuby but i'm getting the below error when trying to load the extension:

C:/Users/PENTEST-SG/AppData/Roaming/BurpSuite/bapps/5f46fe766e9c435992c610160bb53cba/uploader.rb:225: warning: `+' after local variable or literal is interpreted as binary operator
C:/Users/PENTEST-SG/AppData/Roaming/BurpSuite/bapps/5f46fe766e9c435992c610160bb53cba/uploader.rb:225: warning: even though it seems like unary operator
LoadError: no such file to load -- base64
  require at org/jruby/RubyKernel.java:955
   <main> at C:/Users/PENTEST-SG/AppData/Roaming/BurpSuite/bapps/5f46fe766e9c435992c610160bb53cba/uploader.rb:2
  require at org/jruby/RubyKernel.java:955
   <main> at <script>:1
org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- base64
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
	at burp.mzc.<init>(Unknown Source)
	at burp.ycf.a(Unknown Source)
	at burp.vcf.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- base64
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at RUBY.<main>(C:/Users/PENTEST-SG/AppData/Roaming/BurpSuite/bapps/5f46fe766e9c435992c610160bb53cba/uploader.rb:2)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at RUBY.<main>(<script>:1)

thanks

**Comment by thec00n** [comment]
Hmm that's odd. You can try an older jruby. Also you could try: https://stackoverflow.com/questions/46714594/loaderror-cannot-load-such-file-base64
